"""Test numerical equivalence of turn probability computation.

Compares optimized implementation against a pre-computed baseline to ensure
the mathematical output is unchanged after performance optimizations.

The baseline is generated by scripts/generate_turn_prob_baseline.py and stored
in tests/data/turn_prob_baseline.json.
"""

import json
import os
import sys
from pathlib import Path

import numpy as np
import pytest

project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(project_root, "src"))

from pednstream.utils.network_env_generator import NetworkEnvGenerator

BASELINE_PATH = Path(__file__).resolve().parent / "data" / "turn_prob_baseline.json"


@pytest.fixture(scope="module")
def baseline():
    """Load the pre-computed baseline."""
    if not BASELINE_PATH.exists():
        pytest.skip(
            f"Baseline file not found at {BASELINE_PATH}. "
            "Run scripts/generate_turn_prob_baseline.py first."
        )
    with open(BASELINE_PATH) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def simulation_result(baseline):
    """Run a simulation with the same config as the baseline."""
    config = baseline["config"]
    np.random.seed(config["seed"])
    env = NetworkEnvGenerator(config["data_dir"])
    network = env.create_network(verbose=False)

    max_step = max(int(s) for s in baseline["checkpoints"].keys())
    results = {}

    for t in range(1, max_step + 1):
        network.network_loading(t)

        if str(t) in baseline["checkpoints"]:
            checkpoint = {"node_turn_probs": {}, "turning_fractions": {}}
            pf = network.path_finder

            for node_id in pf.nodes_in_paths:
                node = network.nodes[node_id]
                if node.source_num > 2:
                    if hasattr(node, "node_turn_probs"):
                        node_probs = {}
                        for od_pair, turns in node.node_turn_probs.items():
                            od_key = f"{od_pair[0]}_{od_pair[1]}"
                            turn_probs = {}
                            for turn, prob in turns.items():
                                turn_key = f"{turn[0]}_{turn[1]}"
                                turn_probs[turn_key] = float(prob)
                            node_probs[od_key] = turn_probs
                        checkpoint["node_turn_probs"][str(node_id)] = node_probs

                    if node.turning_fractions is not None:
                        checkpoint["turning_fractions"][str(node_id)] = (
                            node.turning_fractions.tolist()
                        )

            results[str(t)] = checkpoint

    return results


class TestTurnProbEquivalence:
    """Test that turn probabilities match the pre-computed baseline."""

    TOLERANCE = 1e-10

    def test_all_checkpoint_steps_present(self, baseline, simulation_result):
        """Verify all checkpoint steps are present in the simulation result."""
        for step in baseline["checkpoints"]:
            assert step in simulation_result, (
                f"Missing checkpoint step {step} in simulation result"
            )

    def test_node_turn_probs_match(self, baseline, simulation_result):
        """Verify turn probabilities match at all checkpoints."""
        mismatches = []

        for step, expected in baseline["checkpoints"].items():
            actual = simulation_result[step]

            for node_id, expected_probs in expected["node_turn_probs"].items():
                if node_id not in actual["node_turn_probs"]:
                    mismatches.append(
                        f"Step {step}, Node {node_id}: missing in actual"
                    )
                    continue

                actual_probs = actual["node_turn_probs"][node_id]

                for od_key, expected_turns in expected_probs.items():
                    if od_key not in actual_probs:
                        mismatches.append(
                            f"Step {step}, Node {node_id}, OD {od_key}: missing"
                        )
                        continue

                    actual_turns = actual_probs[od_key]

                    for turn_key, expected_val in expected_turns.items():
                        if turn_key not in actual_turns:
                            mismatches.append(
                                f"Step {step}, Node {node_id}, OD {od_key}, "
                                f"Turn {turn_key}: missing"
                            )
                            continue

                        actual_val = actual_turns[turn_key]
                        if not np.isclose(
                            expected_val, actual_val, atol=self.TOLERANCE
                        ):
                            mismatches.append(
                                f"Step {step}, Node {node_id}, OD {od_key}, "
                                f"Turn {turn_key}: expected {expected_val}, "
                                f"got {actual_val}"
                            )

        if mismatches:
            msg = f"{len(mismatches)} mismatch(es):\n" + "\n".join(
                mismatches[:20]
            )
            pytest.fail(msg)

    def test_turning_fractions_match(self, baseline, simulation_result):
        """Verify turning fractions match at all checkpoints."""
        mismatches = []

        for step, expected in baseline["checkpoints"].items():
            actual = simulation_result[step]

            for node_id, expected_fracs in expected["turning_fractions"].items():
                if node_id not in actual["turning_fractions"]:
                    mismatches.append(
                        f"Step {step}, Node {node_id}: missing in actual"
                    )
                    continue

                actual_fracs = actual["turning_fractions"][node_id]
                expected_arr = np.array(expected_fracs)
                actual_arr = np.array(actual_fracs)

                if not np.allclose(
                    expected_arr, actual_arr, atol=self.TOLERANCE
                ):
                    diff = np.abs(expected_arr - actual_arr)
                    max_diff = np.max(diff)
                    mismatches.append(
                        f"Step {step}, Node {node_id}: max diff {max_diff:.2e}"
                    )

        if mismatches:
            msg = f"{len(mismatches)} mismatch(es):\n" + "\n".join(
                mismatches[:20]
            )
            pytest.fail(msg)

    def test_no_extra_nodes(self, baseline, simulation_result):
        """Verify no extra nodes appear in the optimized result."""
        for step in baseline["checkpoints"]:
            expected_nodes = set(
                baseline["checkpoints"][step]["node_turn_probs"].keys()
            )
            actual_nodes = set(
                simulation_result[step]["node_turn_probs"].keys()
            )
            extra = actual_nodes - expected_nodes
            assert not extra, (
                f"Step {step}: unexpected nodes {extra}"
            )
